install.packages("ProjectTemplate")
install.packages("digest")
install.packages("tibble")
library(ProjectTemplate)
create.project("CRISP-DM-1")
setwd("D:/英国科目/第一学期/CSC8631 - Data Management and Exploratory Data Analysis/CRISP-DM/CRISP-DM-1")
data1 <- read.csv(file.choose())
View(data1)
data2 <- read.csv(file.choose())
data3 <- read.csv(file.choose())
